namespace SHWD.Platform.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangeStructure : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Alarms", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.DataStatistics", "CommandDataId", "dbo.CommandDatas");
            DropForeignKey("dbo.DataStatistics", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.DataStatistics", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.DataStatistics", "ProjectId", "dbo.Project");
            DropForeignKey("dbo.MonitorDatas", "CommandDataId", "dbo.CommandDatas");
            DropForeignKey("dbo.MonitorDatas", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.MonitorDatas", "ProjectId", "dbo.Project");
            DropForeignKey("dbo.ProtocolDatas", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.ProtocolDatas", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.ProtocolDatas", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.MonitorDatas", "ProtocolDataId", "dbo.ProtocolDatas");
            DropForeignKey("dbo.RunningTimes", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.RunningTimes", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.RunningTimes", "ProjectId", "dbo.Project");
            DropForeignKey("dbo.Device", "OriginalDeviceId", "dbo.Device");
            DropForeignKey("dbo.Alarms", "AlarmDeviceId", "dbo.Device");
            DropForeignKey("dbo.DeviceMaintenances", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.Photos", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.Photos", "PhtotDevice_Id", "dbo.Device");
            DropForeignKey("dbo.CommandTasks", "TaskDeviceId", "dbo.Device");
            DropForeignKey("dbo.RestaurantDevice", "Id", "dbo.Device");
            DropForeignKey("dbo.Device", "CameraId", "dbo.Cameras");
            DropForeignKey("dbo.SysDictionaries", "ParentDictionaryId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Cameras", "AccessTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.DeviceTypes", "FieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.DeviceTypes", "SubFieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Protocols", "FieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Protocols", "SubFieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Photos", "PhotoTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "DistrictId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "ProjectStageId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "TypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "AlarmTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Cameras", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Device", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Project", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.UserDictionaries", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.CateringCompanies", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.LampblackDeviceModels", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Departments", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.DeviceMaintenances", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.WdUser", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Permissions", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.WdRoles", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Modules", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Photos", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.CommandTasks", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.UserConfigs", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Device", "DeviceTypeId", "dbo.DeviceTypes");
            DropForeignKey("dbo.FirmwareSetFirmware", "FirmwareId", "dbo.FirmwareSets");
            DropForeignKey("dbo.Device", "FirmwareSetId", "dbo.FirmwareSets");
            DropForeignKey("dbo.ProtocolFirmware", "FirmwareId", "dbo.Firmwares");
            DropForeignKey("dbo.FirmwareSetFirmware", "FirmwareSetId", "dbo.Firmwares");
            DropForeignKey("dbo.ProtocolFirmware", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.ProtocolCommands", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.ProtocolStructures", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.CommandDataProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.CommandDefinitions", "Command_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.SysConfigProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.CommandDataProtocolCommands", "CommandData_Id", "dbo.CommandDatas");
            DropForeignKey("dbo.SysConfigs", "ParentSysConfigId", "dbo.SysConfigs");
            DropForeignKey("dbo.SysConfigProtocolCommands", "SysConfig_Id", "dbo.SysConfigs");
            DropForeignKey("dbo.Device", "ProjectId", "dbo.Project");
            DropForeignKey("dbo.ParticulateMatterProject", "Id", "dbo.Project");
            DropForeignKey("dbo.HotelRestaurant", "Id", "dbo.Project");
            DropForeignKey("dbo.UserDictionaries", "ParentDictionaryId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "DistrictId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "StreetId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "AddressId", "dbo.UserDictionaries");
            DropForeignKey("dbo.LampblackUser", "CateringCompanyId", "dbo.CateringCompanies");
            DropForeignKey("dbo.HotelRestaurant", "RaletedCompanyId", "dbo.CateringCompanies");
            DropForeignKey("dbo.RestaurantDevice", "DeviceModelId", "dbo.LampblackDeviceModels");
            DropForeignKey("dbo.LampblackUser", "DepartmentId", "dbo.Departments");
            DropForeignKey("dbo.UserPermission", "UserId", "dbo.WdUser");
            DropForeignKey("dbo.UserRole", "UserId", "dbo.WdUser");
            DropForeignKey("dbo.DeviceMaintenances", "MaintenanceUserId", "dbo.WdUser");
            DropForeignKey("dbo.LampblackUser", "Id", "dbo.WdUser");
            DropForeignKey("dbo.Permissions", "ParentPermissionId", "dbo.Permissions");
            DropForeignKey("dbo.RolePermission", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.Modules", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.WdRoles", "ParentRoleId", "dbo.WdRoles");
            DropForeignKey("dbo.RolePermission", "RoleId", "dbo.WdRoles");
            DropForeignKey("dbo.UserRole", "RoleId", "dbo.WdRoles");
            DropForeignKey("dbo.Modules", "ParentModuleId", "dbo.Modules");
            DropForeignKey("dbo.ProtocolDatas", "CommandTask_Id", "dbo.CommandTasks");
            DropForeignKey("dbo.UserConfigs", "ParentUserConfigId", "dbo.UserConfigs");
            DropIndex("dbo.Alarms", new[] { "DomainId" });
            DropIndex("dbo.DataStatistics", new[] { "CommandDataId" });
            DropIndex("dbo.DataStatistics", "Ix_Project_Device_UpdateTime");
            DropIndex("dbo.DataStatistics", new[] { "DeviceId" });
            DropIndex("dbo.DataStatistics", new[] { "DomainId" });
            DropIndex("dbo.MonitorDatas", "Ix_Project_ProtocolData_UpdateTime");
            DropIndex("dbo.MonitorDatas", new[] { "CommandDataId" });
            DropIndex("dbo.MonitorDatas", new[] { "DomainId" });
            DropIndex("dbo.ProtocolDatas", "Ix_Device_UpdateTime");
            DropIndex("dbo.ProtocolDatas", new[] { "ProtocolId" });
            DropIndex("dbo.ProtocolDatas", new[] { "DomainId" });
            DropIndex("dbo.RunningTimes", new[] { "ProjectId" });
            DropIndex("dbo.RunningTimes", new[] { "DeviceId" });
            DropIndex("dbo.RunningTimes", new[] { "DomainId" });
            DropPrimaryKey("dbo.Alarms");
            DropPrimaryKey("dbo.Device");
            DropPrimaryKey("dbo.Cameras");
            DropPrimaryKey("dbo.SysDictionaries");
            DropPrimaryKey("dbo.Domains");
            DropPrimaryKey("dbo.DeviceTypes");
            DropPrimaryKey("dbo.FirmwareSets");
            DropPrimaryKey("dbo.Firmwares");
            DropPrimaryKey("dbo.Protocols");
            DropPrimaryKey("dbo.ProtocolCommands");
            DropPrimaryKey("dbo.CommandDatas");
            DropPrimaryKey("dbo.CommandDefinitions");
            DropPrimaryKey("dbo.SysConfigs");
            DropPrimaryKey("dbo.ProtocolStructures");
            DropPrimaryKey("dbo.Project");
            DropPrimaryKey("dbo.UserDictionaries");
            DropPrimaryKey("dbo.CateringCompanies");
            DropPrimaryKey("dbo.LampblackDeviceModels");
            DropPrimaryKey("dbo.DataStatistics");
            DropPrimaryKey("dbo.Departments");
            DropPrimaryKey("dbo.DeviceMaintenances");
            DropPrimaryKey("dbo.WdUser");
            DropPrimaryKey("dbo.Permissions");
            DropPrimaryKey("dbo.WdRoles");
            DropPrimaryKey("dbo.Modules");
            DropPrimaryKey("dbo.MonitorDatas");
            DropPrimaryKey("dbo.ProtocolDatas");
            DropPrimaryKey("dbo.Photos");
            DropPrimaryKey("dbo.RunningTimes");
            DropPrimaryKey("dbo.CommandTasks");
            DropPrimaryKey("dbo.UserConfigs");
            AddColumn("dbo.Device", "Identity", c => c.Long(nullable: false, identity: true));
            AddColumn("dbo.Project", "Identity", c => c.Long(nullable: false, identity: true));
            AddColumn("dbo.DataStatistics", "ProjectIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.DataStatistics", "DeviceIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.MonitorDatas", "DeviceIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.MonitorDatas", "ProjectIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.ProtocolDatas", "DeviceIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.RunningTimes", "ProjectIdentity", c => c.Long(nullable: false));
            AddColumn("dbo.RunningTimes", "DeviceIdentity", c => c.Long(nullable: false));
            AlterColumn("dbo.Alarms", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Device", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Cameras", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.SysDictionaries", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Domains", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.DeviceTypes", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.FirmwareSets", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Firmwares", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Protocols", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ProtocolCommands", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.CommandDatas", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.CommandDefinitions", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.SysConfigs", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ProtocolStructures", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Project", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.UserDictionaries", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.CateringCompanies", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.LampblackDeviceModels", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.DataStatistics", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Departments", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.DeviceMaintenances", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.WdUser", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Permissions", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.WdRoles", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Modules", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.MonitorDatas", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.MonitorDatas", "ProtocolDataId", c => c.Long(nullable: false));
            AlterColumn("dbo.ProtocolDatas", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Photos", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.RunningTimes", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.CommandTasks", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.UserConfigs", "Id", c => c.Guid(nullable: false, identity: true));
            AddPrimaryKey("dbo.Alarms", "Id");
            AddPrimaryKey("dbo.Device", "Id");
            AddPrimaryKey("dbo.Cameras", "Id");
            AddPrimaryKey("dbo.SysDictionaries", "Id");
            AddPrimaryKey("dbo.Domains", "Id");
            AddPrimaryKey("dbo.DeviceTypes", "Id");
            AddPrimaryKey("dbo.FirmwareSets", "Id");
            AddPrimaryKey("dbo.Firmwares", "Id");
            AddPrimaryKey("dbo.Protocols", "Id");
            AddPrimaryKey("dbo.ProtocolCommands", "Id");
            AddPrimaryKey("dbo.CommandDatas", "Id");
            AddPrimaryKey("dbo.CommandDefinitions", "Id");
            AddPrimaryKey("dbo.SysConfigs", "Id");
            AddPrimaryKey("dbo.ProtocolStructures", "Id");
            AddPrimaryKey("dbo.Project", "Id");
            AddPrimaryKey("dbo.UserDictionaries", "Id");
            AddPrimaryKey("dbo.CateringCompanies", "Id");
            AddPrimaryKey("dbo.LampblackDeviceModels", "Id");
            AddPrimaryKey("dbo.DataStatistics", "Id");
            AddPrimaryKey("dbo.Departments", "Id");
            AddPrimaryKey("dbo.DeviceMaintenances", "Id");
            AddPrimaryKey("dbo.WdUser", "Id");
            AddPrimaryKey("dbo.Permissions", "Id");
            AddPrimaryKey("dbo.WdRoles", "Id");
            AddPrimaryKey("dbo.Modules", "Id");
            AddPrimaryKey("dbo.MonitorDatas", "Id");
            AddPrimaryKey("dbo.ProtocolDatas", "Id");
            AddPrimaryKey("dbo.Photos", "Id");
            AddPrimaryKey("dbo.RunningTimes", "Id");
            AddPrimaryKey("dbo.CommandTasks", "Id");
            AddPrimaryKey("dbo.UserConfigs", "Id");
            CreateIndex("dbo.Device", "Identity", unique: true, clustered: true, name: "Index_Device_Identity");
            CreateIndex("dbo.Project", "Identity", unique: true, clustered: true, name: "Index_Project_Identity");
            CreateIndex("dbo.DataStatistics", new[] { "ProjectIdentity", "DeviceIdentity", "UpdateTime" }, name: "Ix_Project_Device_UpdateTime");
            //CreateIndex("dbo.MonitorDatas", new[] { "ProjectIdentity", "DeviceIdentity", "ProtocolDataId" }, name: "Ix_Project_Device_ProtocolData");
            CreateIndex("dbo.ProtocolDatas", new[] { "DeviceIdentity", "UpdateTime" }, name: "Ix_Device_UpdateTime");
            AddForeignKey("dbo.Device", "OriginalDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Alarms", "AlarmDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.DeviceMaintenances", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Photos", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Photos", "PhtotDevice_Id", "dbo.Device", "Id");
            AddForeignKey("dbo.CommandTasks", "TaskDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.RestaurantDevice", "Id", "dbo.Device", "Id");
            AddForeignKey("dbo.Device", "CameraId", "dbo.Cameras", "Id");
            AddForeignKey("dbo.SysDictionaries", "ParentDictionaryId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Cameras", "AccessTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.DeviceTypes", "FieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.DeviceTypes", "SubFieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Protocols", "FieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Protocols", "SubFieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Photos", "PhotoTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "DistrictId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "ProjectStageId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "TypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "AlarmTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Cameras", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Device", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Project", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.UserDictionaries", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.CateringCompanies", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.LampblackDeviceModels", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Departments", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.DeviceMaintenances", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.WdUser", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Permissions", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.WdRoles", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Modules", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Photos", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.CommandTasks", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.UserConfigs", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Device", "DeviceTypeId", "dbo.DeviceTypes", "Id");
            AddForeignKey("dbo.FirmwareSetFirmware", "FirmwareId", "dbo.FirmwareSets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Device", "FirmwareSetId", "dbo.FirmwareSets", "Id");
            AddForeignKey("dbo.ProtocolFirmware", "FirmwareId", "dbo.Firmwares", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FirmwareSetFirmware", "FirmwareSetId", "dbo.Firmwares", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProtocolFirmware", "ProtocolId", "dbo.Protocols", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProtocolCommands", "ProtocolId", "dbo.Protocols", "Id");
            AddForeignKey("dbo.ProtocolStructures", "ProtocolId", "dbo.Protocols", "Id");
            AddForeignKey("dbo.CommandDataProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommandDefinitions", "Command_Id", "dbo.ProtocolCommands", "Id");
            AddForeignKey("dbo.SysConfigProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommandDataProtocolCommands", "CommandData_Id", "dbo.CommandDatas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SysConfigs", "ParentSysConfigId", "dbo.SysConfigs", "Id");
            AddForeignKey("dbo.SysConfigProtocolCommands", "SysConfig_Id", "dbo.SysConfigs", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Device", "ProjectId", "dbo.Project", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "Id", "dbo.Project", "Id");
            AddForeignKey("dbo.HotelRestaurant", "Id", "dbo.Project", "Id");
            AddForeignKey("dbo.UserDictionaries", "ParentDictionaryId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "DistrictId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "StreetId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "AddressId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.LampblackUser", "CateringCompanyId", "dbo.CateringCompanies", "Id");
            AddForeignKey("dbo.HotelRestaurant", "RaletedCompanyId", "dbo.CateringCompanies", "Id");
            AddForeignKey("dbo.RestaurantDevice", "DeviceModelId", "dbo.LampblackDeviceModels", "Id");
            AddForeignKey("dbo.LampblackUser", "DepartmentId", "dbo.Departments", "Id");
            AddForeignKey("dbo.UserPermission", "UserId", "dbo.WdUser", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRole", "UserId", "dbo.WdUser", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceMaintenances", "MaintenanceUserId", "dbo.WdUser", "Id");
            AddForeignKey("dbo.LampblackUser", "Id", "dbo.WdUser", "Id");
            AddForeignKey("dbo.Permissions", "ParentPermissionId", "dbo.Permissions", "Id");
            AddForeignKey("dbo.RolePermission", "PermissionId", "dbo.Permissions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permissions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Modules", "PermissionId", "dbo.Permissions", "Id");
            AddForeignKey("dbo.WdRoles", "ParentRoleId", "dbo.WdRoles", "Id");
            AddForeignKey("dbo.RolePermission", "RoleId", "dbo.WdRoles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRole", "RoleId", "dbo.WdRoles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Modules", "ParentModuleId", "dbo.Modules", "Id");
            AddForeignKey("dbo.ProtocolDatas", "CommandTask_Id", "dbo.CommandTasks", "Id");
            AddForeignKey("dbo.UserConfigs", "ParentUserConfigId", "dbo.UserConfigs", "Id");
            DropColumn("dbo.DataStatistics", "ProjectId");
            DropColumn("dbo.DataStatistics", "DeviceId");
            DropColumn("dbo.MonitorDatas", "ProjectId");
            DropColumn("dbo.ProtocolDatas", "DeviceId");
            DropColumn("dbo.RunningTimes", "ProjectId");
            DropColumn("dbo.RunningTimes", "DeviceId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RunningTimes", "DeviceId", c => c.Guid(nullable: false));
            AddColumn("dbo.RunningTimes", "ProjectId", c => c.Guid(nullable: false));
            AddColumn("dbo.ProtocolDatas", "DeviceId", c => c.Guid(nullable: false));
            AddColumn("dbo.MonitorDatas", "ProjectId", c => c.Guid());
            AddColumn("dbo.DataStatistics", "DeviceId", c => c.Guid(nullable: false));
            AddColumn("dbo.DataStatistics", "ProjectId", c => c.Guid());
            DropForeignKey("dbo.UserConfigs", "ParentUserConfigId", "dbo.UserConfigs");
            DropForeignKey("dbo.ProtocolDatas", "CommandTask_Id", "dbo.CommandTasks");
            DropForeignKey("dbo.Modules", "ParentModuleId", "dbo.Modules");
            DropForeignKey("dbo.UserRole", "RoleId", "dbo.WdRoles");
            DropForeignKey("dbo.RolePermission", "RoleId", "dbo.WdRoles");
            DropForeignKey("dbo.WdRoles", "ParentRoleId", "dbo.WdRoles");
            DropForeignKey("dbo.Modules", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.RolePermission", "PermissionId", "dbo.Permissions");
            DropForeignKey("dbo.Permissions", "ParentPermissionId", "dbo.Permissions");
            DropForeignKey("dbo.LampblackUser", "Id", "dbo.WdUser");
            DropForeignKey("dbo.DeviceMaintenances", "MaintenanceUserId", "dbo.WdUser");
            DropForeignKey("dbo.UserRole", "UserId", "dbo.WdUser");
            DropForeignKey("dbo.UserPermission", "UserId", "dbo.WdUser");
            DropForeignKey("dbo.LampblackUser", "DepartmentId", "dbo.Departments");
            DropForeignKey("dbo.RestaurantDevice", "DeviceModelId", "dbo.LampblackDeviceModels");
            DropForeignKey("dbo.HotelRestaurant", "RaletedCompanyId", "dbo.CateringCompanies");
            DropForeignKey("dbo.LampblackUser", "CateringCompanyId", "dbo.CateringCompanies");
            DropForeignKey("dbo.HotelRestaurant", "AddressId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "StreetId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "DistrictId", "dbo.UserDictionaries");
            DropForeignKey("dbo.UserDictionaries", "ParentDictionaryId", "dbo.UserDictionaries");
            DropForeignKey("dbo.HotelRestaurant", "Id", "dbo.Project");
            DropForeignKey("dbo.ParticulateMatterProject", "Id", "dbo.Project");
            DropForeignKey("dbo.Device", "ProjectId", "dbo.Project");
            DropForeignKey("dbo.SysConfigProtocolCommands", "SysConfig_Id", "dbo.SysConfigs");
            DropForeignKey("dbo.SysConfigs", "ParentSysConfigId", "dbo.SysConfigs");
            DropForeignKey("dbo.CommandDataProtocolCommands", "CommandData_Id", "dbo.CommandDatas");
            DropForeignKey("dbo.SysConfigProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.CommandDefinitions", "Command_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.CommandDataProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands");
            DropForeignKey("dbo.ProtocolStructures", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.ProtocolCommands", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.ProtocolFirmware", "ProtocolId", "dbo.Protocols");
            DropForeignKey("dbo.FirmwareSetFirmware", "FirmwareSetId", "dbo.Firmwares");
            DropForeignKey("dbo.ProtocolFirmware", "FirmwareId", "dbo.Firmwares");
            DropForeignKey("dbo.Device", "FirmwareSetId", "dbo.FirmwareSets");
            DropForeignKey("dbo.FirmwareSetFirmware", "FirmwareId", "dbo.FirmwareSets");
            DropForeignKey("dbo.Device", "DeviceTypeId", "dbo.DeviceTypes");
            DropForeignKey("dbo.UserConfigs", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.CommandTasks", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Photos", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Modules", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.WdRoles", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Permissions", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.WdUser", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.DeviceMaintenances", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Departments", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.LampblackDeviceModels", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.CateringCompanies", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.UserDictionaries", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Project", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Device", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.Cameras", "DomainId", "dbo.Domains");
            DropForeignKey("dbo.ParticulateMatterProject", "AlarmTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "TypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "ProjectStageId", "dbo.SysDictionaries");
            DropForeignKey("dbo.ParticulateMatterProject", "DistrictId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Photos", "PhotoTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Protocols", "SubFieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Protocols", "FieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.DeviceTypes", "SubFieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.DeviceTypes", "FieldId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Cameras", "AccessTypeId", "dbo.SysDictionaries");
            DropForeignKey("dbo.SysDictionaries", "ParentDictionaryId", "dbo.SysDictionaries");
            DropForeignKey("dbo.Device", "CameraId", "dbo.Cameras");
            DropForeignKey("dbo.RestaurantDevice", "Id", "dbo.Device");
            DropForeignKey("dbo.CommandTasks", "TaskDeviceId", "dbo.Device");
            DropForeignKey("dbo.Photos", "PhtotDevice_Id", "dbo.Device");
            DropForeignKey("dbo.Photos", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.DeviceMaintenances", "DeviceId", "dbo.Device");
            DropForeignKey("dbo.Alarms", "AlarmDeviceId", "dbo.Device");
            DropForeignKey("dbo.Device", "OriginalDeviceId", "dbo.Device");
            DropIndex("dbo.ProtocolDatas", "Ix_Device_UpdateTime");
            DropIndex("dbo.MonitorDatas", "Ix_Project_Device_ProtocolData");
            DropIndex("dbo.DataStatistics", "Ix_Project_Device_UpdateTime");
            DropIndex("dbo.Project", "Index_Project_Identity");
            DropIndex("dbo.Device", "Index_Device_Identity");
            DropPrimaryKey("dbo.UserConfigs");
            DropPrimaryKey("dbo.CommandTasks");
            DropPrimaryKey("dbo.RunningTimes");
            DropPrimaryKey("dbo.Photos");
            DropPrimaryKey("dbo.ProtocolDatas");
            DropPrimaryKey("dbo.MonitorDatas");
            DropPrimaryKey("dbo.Modules");
            DropPrimaryKey("dbo.WdRoles");
            DropPrimaryKey("dbo.Permissions");
            DropPrimaryKey("dbo.WdUser");
            DropPrimaryKey("dbo.DeviceMaintenances");
            DropPrimaryKey("dbo.Departments");
            DropPrimaryKey("dbo.DataStatistics");
            DropPrimaryKey("dbo.LampblackDeviceModels");
            DropPrimaryKey("dbo.CateringCompanies");
            DropPrimaryKey("dbo.UserDictionaries");
            DropPrimaryKey("dbo.Project");
            DropPrimaryKey("dbo.ProtocolStructures");
            DropPrimaryKey("dbo.SysConfigs");
            DropPrimaryKey("dbo.CommandDefinitions");
            DropPrimaryKey("dbo.CommandDatas");
            DropPrimaryKey("dbo.ProtocolCommands");
            DropPrimaryKey("dbo.Protocols");
            DropPrimaryKey("dbo.Firmwares");
            DropPrimaryKey("dbo.FirmwareSets");
            DropPrimaryKey("dbo.DeviceTypes");
            DropPrimaryKey("dbo.Domains");
            DropPrimaryKey("dbo.SysDictionaries");
            DropPrimaryKey("dbo.Cameras");
            DropPrimaryKey("dbo.Device");
            DropPrimaryKey("dbo.Alarms");
            AlterColumn("dbo.UserConfigs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.CommandTasks", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.RunningTimes", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Photos", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProtocolDatas", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.MonitorDatas", "ProtocolDataId", c => c.Guid(nullable: false));
            AlterColumn("dbo.MonitorDatas", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Modules", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.WdRoles", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Permissions", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.WdUser", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.DeviceMaintenances", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Departments", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.DataStatistics", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.LampblackDeviceModels", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.CateringCompanies", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.UserDictionaries", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Project", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProtocolStructures", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SysConfigs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.CommandDefinitions", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.CommandDatas", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ProtocolCommands", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Protocols", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Firmwares", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.FirmwareSets", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.DeviceTypes", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Domains", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SysDictionaries", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Cameras", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Device", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Alarms", "Id", c => c.Guid(nullable: false));
            DropColumn("dbo.RunningTimes", "DeviceIdentity");
            DropColumn("dbo.RunningTimes", "ProjectIdentity");
            DropColumn("dbo.ProtocolDatas", "DeviceIdentity");
            DropColumn("dbo.MonitorDatas", "ProjectIdentity");
            DropColumn("dbo.MonitorDatas", "DeviceIdentity");
            DropColumn("dbo.DataStatistics", "DeviceIdentity");
            DropColumn("dbo.DataStatistics", "ProjectIdentity");
            DropColumn("dbo.Project", "Identity");
            DropColumn("dbo.Device", "Identity");
            AddPrimaryKey("dbo.UserConfigs", "Id");
            AddPrimaryKey("dbo.CommandTasks", "Id");
            AddPrimaryKey("dbo.RunningTimes", "Id");
            AddPrimaryKey("dbo.Photos", "Id");
            AddPrimaryKey("dbo.ProtocolDatas", "Id");
            AddPrimaryKey("dbo.MonitorDatas", "Id");
            AddPrimaryKey("dbo.Modules", "Id");
            AddPrimaryKey("dbo.WdRoles", "Id");
            AddPrimaryKey("dbo.Permissions", "Id");
            AddPrimaryKey("dbo.WdUser", "Id");
            AddPrimaryKey("dbo.DeviceMaintenances", "Id");
            AddPrimaryKey("dbo.Departments", "Id");
            AddPrimaryKey("dbo.DataStatistics", "Id");
            AddPrimaryKey("dbo.LampblackDeviceModels", "Id");
            AddPrimaryKey("dbo.CateringCompanies", "Id");
            AddPrimaryKey("dbo.UserDictionaries", "Id");
            AddPrimaryKey("dbo.Project", "Id");
            AddPrimaryKey("dbo.ProtocolStructures", "Id");
            AddPrimaryKey("dbo.SysConfigs", "Id");
            AddPrimaryKey("dbo.CommandDefinitions", "Id");
            AddPrimaryKey("dbo.CommandDatas", "Id");
            AddPrimaryKey("dbo.ProtocolCommands", "Id");
            AddPrimaryKey("dbo.Protocols", "Id");
            AddPrimaryKey("dbo.Firmwares", "Id");
            AddPrimaryKey("dbo.FirmwareSets", "Id");
            AddPrimaryKey("dbo.DeviceTypes", "Id");
            AddPrimaryKey("dbo.Domains", "Id");
            AddPrimaryKey("dbo.SysDictionaries", "Id");
            AddPrimaryKey("dbo.Cameras", "Id");
            AddPrimaryKey("dbo.Device", "Id");
            AddPrimaryKey("dbo.Alarms", "Id");
            CreateIndex("dbo.RunningTimes", "DomainId");
            CreateIndex("dbo.RunningTimes", "DeviceId");
            CreateIndex("dbo.RunningTimes", "ProjectId");
            CreateIndex("dbo.ProtocolDatas", "DomainId");
            CreateIndex("dbo.ProtocolDatas", "ProtocolId");
            CreateIndex("dbo.ProtocolDatas", new[] { "DeviceId", "UpdateTime" }, name: "Ix_Device_UpdateTime");
            CreateIndex("dbo.MonitorDatas", "DomainId");
            CreateIndex("dbo.MonitorDatas", "CommandDataId");
            CreateIndex("dbo.MonitorDatas", new[] { "ProjectId", "ProtocolDataId", "UpdateTime" }, name: "Ix_Project_ProtocolData_UpdateTime");
            CreateIndex("dbo.DataStatistics", "DomainId");
            CreateIndex("dbo.DataStatistics", "DeviceId");
            CreateIndex("dbo.DataStatistics", new[] { "ProjectId", "UpdateTime" }, name: "Ix_Project_Device_UpdateTime");
            CreateIndex("dbo.DataStatistics", "CommandDataId");
            CreateIndex("dbo.Alarms", "DomainId");
            AddForeignKey("dbo.UserConfigs", "ParentUserConfigId", "dbo.UserConfigs", "Id");
            AddForeignKey("dbo.ProtocolDatas", "CommandTask_Id", "dbo.CommandTasks", "Id");
            AddForeignKey("dbo.Modules", "ParentModuleId", "dbo.Modules", "Id");
            AddForeignKey("dbo.UserRole", "RoleId", "dbo.WdRoles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RolePermission", "RoleId", "dbo.WdRoles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WdRoles", "ParentRoleId", "dbo.WdRoles", "Id");
            AddForeignKey("dbo.Modules", "PermissionId", "dbo.Permissions", "Id");
            AddForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permissions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RolePermission", "PermissionId", "dbo.Permissions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permissions", "ParentPermissionId", "dbo.Permissions", "Id");
            AddForeignKey("dbo.LampblackUser", "Id", "dbo.WdUser", "Id");
            AddForeignKey("dbo.DeviceMaintenances", "MaintenanceUserId", "dbo.WdUser", "Id");
            AddForeignKey("dbo.UserRole", "UserId", "dbo.WdUser", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserPermission", "UserId", "dbo.WdUser", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LampblackUser", "DepartmentId", "dbo.Departments", "Id");
            AddForeignKey("dbo.RestaurantDevice", "DeviceModelId", "dbo.LampblackDeviceModels", "Id");
            AddForeignKey("dbo.HotelRestaurant", "RaletedCompanyId", "dbo.CateringCompanies", "Id");
            AddForeignKey("dbo.LampblackUser", "CateringCompanyId", "dbo.CateringCompanies", "Id");
            AddForeignKey("dbo.HotelRestaurant", "AddressId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "StreetId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "DistrictId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.UserDictionaries", "ParentDictionaryId", "dbo.UserDictionaries", "Id");
            AddForeignKey("dbo.HotelRestaurant", "Id", "dbo.Project", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "Id", "dbo.Project", "Id");
            AddForeignKey("dbo.Device", "ProjectId", "dbo.Project", "Id");
            AddForeignKey("dbo.SysConfigProtocolCommands", "SysConfig_Id", "dbo.SysConfigs", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SysConfigs", "ParentSysConfigId", "dbo.SysConfigs", "Id");
            AddForeignKey("dbo.CommandDataProtocolCommands", "CommandData_Id", "dbo.CommandDatas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SysConfigProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommandDefinitions", "Command_Id", "dbo.ProtocolCommands", "Id");
            AddForeignKey("dbo.CommandDataProtocolCommands", "ProtocolCommand_Id", "dbo.ProtocolCommands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProtocolStructures", "ProtocolId", "dbo.Protocols", "Id");
            AddForeignKey("dbo.ProtocolCommands", "ProtocolId", "dbo.Protocols", "Id");
            AddForeignKey("dbo.ProtocolFirmware", "ProtocolId", "dbo.Protocols", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FirmwareSetFirmware", "FirmwareSetId", "dbo.Firmwares", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProtocolFirmware", "FirmwareId", "dbo.Firmwares", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Device", "FirmwareSetId", "dbo.FirmwareSets", "Id");
            AddForeignKey("dbo.FirmwareSetFirmware", "FirmwareId", "dbo.FirmwareSets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Device", "DeviceTypeId", "dbo.DeviceTypes", "Id");
            AddForeignKey("dbo.UserConfigs", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.CommandTasks", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Photos", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Modules", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.WdRoles", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Permissions", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.WdUser", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.DeviceMaintenances", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Departments", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.LampblackDeviceModels", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.CateringCompanies", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.UserDictionaries", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Project", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Device", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.Cameras", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "AlarmTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "TypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "ProjectStageId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.ParticulateMatterProject", "DistrictId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Photos", "PhotoTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Protocols", "SubFieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Protocols", "FieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.DeviceTypes", "SubFieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.DeviceTypes", "FieldId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Cameras", "AccessTypeId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.SysDictionaries", "ParentDictionaryId", "dbo.SysDictionaries", "Id");
            AddForeignKey("dbo.Device", "CameraId", "dbo.Cameras", "Id");
            AddForeignKey("dbo.RestaurantDevice", "Id", "dbo.Device", "Id");
            AddForeignKey("dbo.CommandTasks", "TaskDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Photos", "PhtotDevice_Id", "dbo.Device", "Id");
            AddForeignKey("dbo.Photos", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.DeviceMaintenances", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Alarms", "AlarmDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.Device", "OriginalDeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.RunningTimes", "ProjectId", "dbo.Project", "Id");
            AddForeignKey("dbo.RunningTimes", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.RunningTimes", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.MonitorDatas", "ProtocolDataId", "dbo.ProtocolDatas", "Id");
            AddForeignKey("dbo.ProtocolDatas", "ProtocolId", "dbo.Protocols", "Id");
            AddForeignKey("dbo.ProtocolDatas", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.ProtocolDatas", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.MonitorDatas", "ProjectId", "dbo.Project", "Id");
            AddForeignKey("dbo.MonitorDatas", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.MonitorDatas", "CommandDataId", "dbo.CommandDatas", "Id");
            AddForeignKey("dbo.DataStatistics", "ProjectId", "dbo.Project", "Id");
            AddForeignKey("dbo.DataStatistics", "DomainId", "dbo.Domains", "Id");
            AddForeignKey("dbo.DataStatistics", "DeviceId", "dbo.Device", "Id");
            AddForeignKey("dbo.DataStatistics", "CommandDataId", "dbo.CommandDatas", "Id");
            AddForeignKey("dbo.Alarms", "DomainId", "dbo.Domains", "Id");
        }
    }
}
