//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JingAnWebService.AddEnterBaseInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://standbaseinfo.web.ths.com/", ConfigurationName="AddEnterBaseInfo.IInsertBaseInfo")]
    public interface IInsertBaseInfo {
        
        // CODEGEN: Generating message contract since element name jsons from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse addEnterBaseInfo(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse> addEnterBaseInfoAsync(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addEnterBaseInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addEnterBaseInfo", Namespace="http://standbaseinfo.web.ths.com/", Order=0)]
        public JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoBody Body;
        
        public addEnterBaseInfo() {
        }
        
        public addEnterBaseInfo(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addEnterBaseInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsons;
        
        public addEnterBaseInfoBody() {
        }
        
        public addEnterBaseInfoBody(string jsons) {
            this.jsons = jsons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addEnterBaseInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addEnterBaseInfoResponse", Namespace="http://standbaseinfo.web.ths.com/", Order=0)]
        public JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponseBody Body;
        
        public addEnterBaseInfoResponse() {
        }
        
        public addEnterBaseInfoResponse(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addEnterBaseInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addEnterBaseInfoResponseBody() {
        }
        
        public addEnterBaseInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsertBaseInfoChannel : JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertBaseInfoClient : System.ServiceModel.ClientBase<JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo>, JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo {
        
        public InsertBaseInfoClient() {
        }
        
        public InsertBaseInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertBaseInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertBaseInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertBaseInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo.addEnterBaseInfo(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo request) {
            return base.Channel.addEnterBaseInfo(request);
        }
        
        public string addEnterBaseInfo(string jsons) {
            JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo inValue = new JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo();
            inValue.Body = new JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoBody();
            inValue.Body.jsons = jsons;
            JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse retVal = ((JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo)(this)).addEnterBaseInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse> JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo.addEnterBaseInfoAsync(JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo request) {
            return base.Channel.addEnterBaseInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoResponse> addEnterBaseInfoAsync(string jsons) {
            JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo inValue = new JingAnWebService.AddEnterBaseInfo.addEnterBaseInfo();
            inValue.Body = new JingAnWebService.AddEnterBaseInfo.addEnterBaseInfoBody();
            inValue.Body.jsons = jsons;
            return ((JingAnWebService.AddEnterBaseInfo.IInsertBaseInfo)(this)).addEnterBaseInfoAsync(inValue);
        }
    }
}
